# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0203fba6f6aecb3f32db51e2c6e6bb15ffd8fdb92abce713b100b93855abc1a056556ac606cdcbe8f6d315a86bed424bcfa65535eeef80a5a4fc35b8feef7803

test:
  secret_key_base: 25a8f1df0600423f8e6677be5b3f75d5ad1a82093215aab23dfe07745427c6ae386529ef50557e4351f4fefaf0f45c767533bbcc443349f1810129d311e8533a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
