# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 708741e89d246c17af9d3ea438bee74d5e5b8eae2dcd561412521f51b7401473ed14528fa0c2a0453f815ca1dfc302467648401fc8dfdd4cb83f90836e0a5a56

test:
  secret_key_base: 73cc6f6f85c48e2d8ef02cb1bb6c0ab9c4029cc006dc7b1b8f6001f5e4c28543acc8c791be78a4bd17e50af2df42afa335fef1fe19de6be807ab8e6501c0c52b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
